server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://viaduct.proxy.rlwy.net:28055/railway
    username: root
    password: hG621bH6fHeHEaHfAChb6ghA2FhEcAfA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

# url
api:
  prefix: api/v1